amazon: 'variavel-amazon'
swagger:
  request-url: 'localhost'
contact:
  name: 'Eduardo Zielke'
  url: 'https://www.linkedin.com/in/eduardozielke/'
  email: "zielkeeduardo@gmail.com"
aws:
  region: sa-east-1
  s3:
    buckets:
      customer: zielkebucket


# Logging configurations
#spring:
#  output:
#    ansi:
#      enabled:
#        ALWAYS
#logging:
#  pattern:
#    console:
#      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){magenta} %clr(%-5p) %clr(${PID}){faint} %clr(---){cyan} %clr([%8.15t]){blue} %clr(%-40.40logger{0}){magenta} %clr(:){cyan} %clr(%m){red}%n

#verificar como que faz para mudar as cores quando está usando gradle, na aplicação usando maven parece que funcionou, ver se tem algo a ver.

server:
  error:
    include-stacktrace: on_param
  servlet:
    context-path: /amazon-s3
  port: '7777'
